### ISSUE TITLE
UpWork- Adding TypeScript Strict Mode

### ISSUE THREAD

**Issue by SharjeelSafdar** [grod220/tms-george-fox#15]
Hi @grod220, I saw the [job](https://www.upwork.com/jobs/~01c32808dedf766156) you posted on UpWork for enabling strict mode in TypeScript compiler options.

I have forked your repo and done all the work you want in the forked repo. 
https://github.com/SharjeelSafdar/tms-george-fox

Please, review the code. If you find it appropriate, hire me on UpWork and I'll create a pull request to merge the changes. If you want any changes, I can do that as well.

Looking forward to hearing from you.

**Comment by grod220** [comment]
Nice job. I have a few comments, so I'll hire you via Upwork and we can chat on the PR you create.
